htmlの変更をしました
DaisukeKikukawa/codegym-html pull request #1
Opened 2021-04-08 11:58 UTC by DaisukeKikukawa

2021-04-09 10:45 UTC, TomoakiTANAKA commented
@DaisukeKikukawa 
お疲れ様です。

**index.htmlの詳細なレビューは未実施です。**

後からの案内になりすいませんが、[notion](https://www.notion.so/codegym/1-NRI-abf2a94fe7f84b4d91cf77b2f2f62f57)で更新があり
「初回のPRの提出に関連画像も必要」となっています。

再度画像ファイルのコミットをPRに含めるてください。
お手数ですが画像ファイルの追加も他の指摘と合わせて対応お願いします。

2021-04-09 10:47 UTC, TomoakiTANAKA commented on nri/index.html
> +    <section class="main-visual">
<header>とインデントが揃っていません。
細かいことですが、可読性に関わるので揃えましょう。

vscodeに自動的にフォーマットを揃える機能があるので、検索して使ってみましょう。

2021-04-09 10:47 UTC, TomoakiTANAKA commented on nri/index.html
> +          NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を<br>
改行されているという見た目を気にして、`<br>`を使っていると思いますが、
装飾目的で`<br>`を使うことはほとんどありません。

取り除きましょう。

2021-04-09 10:48 UTC, TomoakiTANAKA commented on nri/index.html
> +</html>
githubの機能で最後に改行があると注意されるので、最終行に改行をいれておきましょう。

2021-04-09 11:48 UTC, Yuzunoha commented on nri/index.html
> +          >
smallタグの改行がおかしいので直しましょう

2021-04-09 11:51 UTC, Yuzunoha commented on nri/index.html
> +          <span></span>
このspanタグは必要でしょうか

2021-04-09 11:53 UTC, Yuzunoha commented on nri/index.html
> +        </p>
htmlファイル内での改行が不規則なので修正しましょう。
個々の長文はpタグ数個に分かれるはずです。本家のサイトを確認しましょう。
https://www.nri.com/jp/company/whats/story06

2021-04-09 12:08 UTC, Yuzunoha commented
画像に関して、 ”html-nriのコピー” フォルダは不要ですね。nriフォルダの中に画像用のフォルダを作って画像関連のファイルを格納してください

2021-04-09 12:09 UTC, Yuzunoha commented
画像の数が足りないですね。フェイスブックのアイコンなど。
あとこれ
![image](https://user-images.githubusercontent.com/22877094/114177840-d5ad6280-9977-11eb-9535-c97d39f01b6a.png)
などは画像で採れないのでキャプチャで取得してください。

2021-04-09 12:12 UTC, Yuzunoha commented on nri/index.html
> +          <li><p>株主・投資家情報（IR）</p></li>
リスト内の<p>タグは不要かと思います。他の個所もみなおしてください。

2021-04-10 01:50 UTC, TomoakiTANAKA commented on nri/index.html
> +        </p>
`<p>`タグはパラグラフ（文章の意味のある1塊）を表現します。

なので、「~を」でちょん切ることはほぼありえません。

今回でいえば、「NRIでは〜DXを「DX2.0」と定義しています。」

までを1つのパラグラフと考えてマークアップするのが良いです。（以下同じ指摘）

2021-04-10 01:52 UTC, TomoakiTANAKA commented
https://github.com/DaisukeKikukawa/codegym-html/pull/1#issuecomment-816636895

が修正されていないようです。
例：
`html-nriのコピー/images/h1_whats_2.jpg`

`html-hriのコピー` に追加した画像が残っています。画像が不要なら消す、必要な画像なら、`nir/images`に移動しましょう。

2021-04-10 01:54 UTC, TomoakiTANAKA commented
![image](https://user-images.githubusercontent.com/1779811/114254559-16928f00-99eb-11eb-9a46-03c242fd6c9e.png)

PDFのアイコンが存在していないようです。
アイコンを追加のうえ、index.htmlを開いたときに表示されるようにしてください。（cssによるスタイリングは不要）。

2021-04-10 02:33 UTC, TomoakiTANAKA commented on nri/index.html
> +    <link rel="stylesheet" href="./css/style.css" />
2つのcssファイルがそん存在しないため、デベロッパーツール上でエラーがでています。
![image](https://user-images.githubusercontent.com/1779811/114254725-04652080-99ec-11eb-9f9c-c3df9407b4ee.png)


基本的によほどの理由がなければ
* 1つのPRでエラーを残さない
というのが基本です。

もし、後から作る予定のファイルだからあえて書いているというのであれば
- PRの説明にその旨書く
- からのファイルでいいのでcssを作っておく
というのがいいです。

ただ、今回は消しておくのが良いです。

2021-04-10 02:33 UTC, TomoakiTANAKA commented on nri/index.html
> +          <li>NRIvoice</li>
細かいですが、本番と差分があります。
本番は、NRIの後に半角スペースがあります。

2021-04-10 02:33 UTC, TomoakiTANAKA commented on nri/index.html
> +          >
改行が治っていません。修正するなら、こんな感じになります。

* smallタグでかこまれているよ、というのがわかりやすいパターン

```suggestion
          <small>
              Copyright(c) Nomura Research Institute, Ltd. All rightsreserved.
          </small>
```

* 短いから1行でやるパターン

```suggestion
          <small>Copyright(c) Nomura Research Institute, Ltd. All rightsreserved.</small>
```

2021-04-10 02:33 UTC, TomoakiTANAKA commented on nri/index.html
> +        <img src="./images/story06_img_01.jpg" alt="" />
alt属性は定義されていますが、alt属性の中身が指定されていません。
どんな画像が設定されているか指定をしましょう。

目が見えない人や検索エンジンに画像の意味を伝える意味があります。

[なぜaltの指定が必要なのかの補足資料](https://www.allegro-inc.com/seo/img-alt-text-seo)

2021-04-12 10:39 UTC, Yuzunoha commented
ユズノハ用メモ
- [ ] 文言があっていること
- [ ] 画像関連ファイルが用意されていること

2021-04-12 11:12 UTC, Yuzunoha commented
facebookやpdfのsvgファイルが無いですね！現状アイコンとかが白黒なので(cssでクラス指定しただけですね)格納しましょう。pdfのsvgファイルはそのものが無ければ似てるのをネットで拾ってくるかキャプチャしましょう。

2021-04-12 11:37 UTC, Yuzunoha commented on nri/index.html
> +          <li>ソリューションサービス</li>
```suggestion
          <li>ソリューション・サービス</li>
```
細かいですが

2021-04-12 11:37 UTC, Yuzunoha commented on nri/index.html
> +          <li>ナレッジインサイト</li>
```suggestion
          <li>ナレッジ・インサイト</li>
```

2021-04-12 11:38 UTC, Yuzunoha commented
本家にある
「前のページに戻る」
が無いですね

2021-04-12 11:41 UTC, Yuzunoha requested changes

2021-04-12 11:41 UTC, Yuzunoha commented on nri/index.html
> +          <li>個人投資家の皆様え</li>
```suggestion
          <li>株式・格付情報</li>
          <li>個人投資家の皆さまへ</li>
```

2021-04-12 11:41 UTC, Yuzunoha commented on nri/index.html
> +          <li>NRI voice</li>
```suggestion
          <li>NRI People</li>
          <li>NRI Voice</li>
```

2021-04-13 12:33 UTC, kai-kou commented
コミットログに`①svg画像の追加`とありますが、HTMLファイルの修正はコミットにありますが、画像ファイルが`images`ディレクトリに追加されていませんでしたので、コミット漏れが無いか確認のうえ、再度、レビュー依頼してください。

2021-04-15 10:23 UTC, TomoakiTANAKA commented
田中レビューメモ
- [ ] 過去の指摘事項が修正されているか？
- [ ] テキストの抜け漏れや誤字はないか？
- [ ] 画像ファイルの抜け漏れはないか？

2021-04-15 10:28 UTC, TomoakiTANAKA commented on nri/images/icon-facebook.svg
> +</svg>
（細かいですが）
ファイルの最終行に改行をいれましょう。（他のsvg画像も見直してみてください。）

2021-04-15 10:28 UTC, TomoakiTANAKA commented on nri/images/icon-facebook.svg
> +</svg>
`</svg>`のあとに改行を入れると、下記のマークがきえますよ！

![image](https://user-images.githubusercontent.com/1779811/114855188-a340b100-9e20-11eb-99e2-30ff07d6ef53.png)

2021-04-15 10:49 UTC, TomoakiTANAKA commented
パンくずリストのHTMLが抜けています

![image](https://user-images.githubusercontent.com/1779811/114857783-a2f5e500-9e23-11eb-8da9-ef781823f40f.png)

2021-04-15 10:56 UTC, TomoakiTANAKA commented on nri/index.html
> +          &gt（7.43MB）<img src="./images/ダウンロード.jpeg" width="30px" height="30px" alt="pdf">
画像パスの指定が間違っており、ファイルが読み込めていません。
パスを修正してください。

![image](https://user-images.githubusercontent.com/1779811/114858139-0d0e8a00-9e24-11eb-95c0-9ddc0bc1bcd5.png)

2021-04-15 10:56 UTC, TomoakiTANAKA commented
サイトマップの記述が抜けています

![image](https://user-images.githubusercontent.com/1779811/114858648-b3f32600-9e24-11eb-999b-278786e6a35d.png)

2021-04-16 11:40 UTC, TomoakiTANAKA commented on nri/index.html
> +</ul>
- [ ] ulのインデントを上の`header`や下の`div`と合わせてください
- [ ] `&gt;`は、ulの箇条書きの内容としてふさわしくないので移動させましょう

```suggestion
<ul>
  <li>NRI トップ&gt;</li>
  <li>企業情報&gt;</li>
  <li> NRIの強み：NRIのデジタルビジネス戦略</li>
</ul>
```

2021-04-17 01:38 UTC, disneyLadySango reviewed
@DaisukeKikukawa 
何点かマークアップの部分でコメントしています。
追加のコメントで申し訳ございませんが、CSS課題の際に手戻りになりそうなところでもあるので、今のうちに対応していただけるとありがたいです🙇‍♂️

整形がしっかりされているのとfontawesomeを使ってiconの実装されていてすごいなと思いました！
あと一歩なので修正していただければと思います！

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +      <h1 class="logo">NRI</h1>
[must]
ここコメント出ていなかったので追加の修正をお願いしますmm

ロゴはSVGを使っているので、そちらに修正をお願い致します！
twitterとかfacebookとかと同じように、`icon-logo.svg`みたいな名前にするとかなり分かりやすくて良いかなと思います！

その上で会社のロゴは見出しとはちょっと意味合いが異なるのと、ここは押すとトップページに飛ぶので`h1`を`a`に変えて以下のようにすると良いです
```
<a href="#"><img src="./images/icon-logo.svg" alt="NRI"></a>
```

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +        <p>NRIのデジタルビジネス戦略</p>
[must]
こちらも追加で対応お願いします🙇‍♂️

ここの文言はこのページの見出しになるので`h1`タグに変更をおねがします！

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +    </div>
[must]
こちらも対応お願いします！

ここぱっと見はリストっぽくないのですが、文章の構造的にはリストなので、`div`タグを `ul`と`li`にそれぞれ変えていただければと思います！

```
<div class="wrapeer-grid"></div> -> <ul class="wrapper-grid"></ul>
<div class="item"></div> -> <li class="item"></li>
```

divでもいいと言えばいいのですが、リスト構造にしておく利点として
「ここのブロックは一つの塊として扱えば良い」
というのが見て分かるので同じような項目が並んでいる時は是非リストを使ってもらえればと思います

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +    </div>
+αですがここ全てリンクがついているので`<a href="#">文字</a>`に修正をお願いします！

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +          <li>&gt;社長メッセージ</li>
[should]
この辺りも大体リンクになっているので`a`タグをつけてもらえると・・・！
ちょっと大変かもしれませんが、この後の課題で手戻り出てしまう可能性があるので
是非先に直していただければと思います！

2021-04-17 01:38 UTC, disneyLadySango commented on nri/index.html
> +        </p>
[must]
こちらですが`p`を使わずにどちらかを使ってもらえればと思います！
`button` or `a`
基本は`button`を使うべきなのですが、別ページへの遷移としてボタンを使う場合もあるので、`a`をボタンに見立てて使うケースも多々あります。
この場合どちらも正しいケースなので、お好きな方を使ってもらえればと思います！

2021-04-17 02:35 UTC, disneyLadySango approved these changes
@DaisukeKikukawa 
お疲れ様です！ご対応ありがとうございます！
１点コメントしましたがマージ前に対応してくれればOKの箇所なのでお願いします！
再度のレビュー依頼は不要ですので、こちらLGTMとさせていただきます！！！

自動整形便利なのでこれからもガッツリ使っていきましょう！

2021-04-17 02:35 UTC, disneyLadySango commented on nri/index.html
> +          <li class="category-list-header">&gt;ナレッジ・インサイト</li>
[must]
ごめんなさい！
ここもマージ前に`a`タグを追加しておいてください！！！
再レビューは不要でOKです！

2021-04-17 04:37 UTC, merged